#!/bin/bash 
echo "__________________"
echo "declaring variabls..."
LM_nameScript=ARM_Linux_Modder
JD_nameScript=ARM_Java7_Downloader
JDK7sf_nameScript=ARM_JDK7sf_Installer
MT_nameScript=ARM_Maptools_Installer
jM_nameScript=ARM_jMonkey_Installer
NF_nameScript=ARM_NoFlo_Installer
KF_nameScript=Key_Fixer
echo "$LM_nameScript is running"
echo "variables for user and home directories" 
 : ${USER?} ${HOME?} 
echo "user is : $USER"
echo "home directory is $HOME"
echo "finding the name of this script and store it to a variable"
LM_fullScriptPath="$(readlink -f $0)"
# deleat last componit from this script and store to another variable
LM_ScriptDirectory="$(dirname $LM_fullScriptPath)"
# print curent working directory then print the newly set variables
echo "Your curent working directory is : $PWD"
echo "The name of this script is : $LM_fullScriptPath"
echo "The path to this script is : $LM_ScriptDirectory"
echo "setting componit path variable"
LM_componitPath=$LM_ScriptDirectory/ARM_Mod/Install_Scripts/Components
LM_downloadPath=$LM_ScriptDirectory/ARM_Mod/Download
echo "$LM_nameScript will use the following file path for script componits"
echo "$LM_componitPath"
echo "$LM_nameScript will use the following file path for downloading files"
echo "$LM_downloadPath"
echo "__________________"
echo "This script is written in the hopes that it will be found useful" 
echo "But without waranty. Use $LM_nameScript to install many extras to your" 
echo "ARM Linux Operating System" 
echo "__________________"
{ 
# confirm with the user 
read -r -p "Do you wish to continue? [y/N] " response 
case "$response" in 
	[yY][eE][sS]|[yY]) 
# if yes, then start risking changes 
		;; 
	*) 
#		 Otherwise exit.. 
	echo "Good Night" 
	exit 
	;; 
esac
} 
echo "making directories"
mkdir -p $LM_componitPath
mkdir -p $LM_downloadPath
# Prompt for which scripts to download or run
echo "$LM_nameScript can download and or run the following"
echo "0 - exit"
echo "1 - run $JD_nameScript [untested]"
echo "2 - run $JDK7sf_nameScript [untested]"
echo "3 - run $MT_nameScript [untested]"
echo "4 - run $jM_nameScript [untested]"
echo "5 - run $NF_nameScript [untested]"
echo "6 - run $KF_nameScript [untested]"
echo "7 - exit"
echo "________________________"
echo "Choose and input a number to continue"
echo "or input no to abort $SAS_MMod"
read -r -p "Which one thing would you like to do? " response
	if [ $response = 1 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/$JD_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 2 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/Install_Scripts/$JDK7sf_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 3 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/$MT_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 4 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/$jM_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 5 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/$NF_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 6 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/$KF_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 7 ] 
then 
		echo "this has yet to be writen"
		echo "exiting now"
		echo exit 
		exit 
	elif [ $response = 0 ] 
then 
		echo "this has yet to be writen"
		echo "exiting now"
		echo exit 
		exit 
	else [ $response = * ] then 
#	 if anything else then exit 
		echo "exiting now"
		echo exit 
		exit 
	fi
exit

