#!/bin/bash 
echo "__________________"
echo "declaring variabls..."
LM_nameScript=ARM_Linux_Modder
JD_nameScript=ARM_JREorJDK7_Downloader
JDK7hf_nameScript=ARM_JDKhf_Installer
JDK7sf_nameScript=ARM_JDKsf_Installer
MT_nameScript=ARM_Maptools_Installer
jM_nameScript=ARM_jMonkey_Installer
NF_nameScript=ARM_NoFlo_Installer
KF_nameScript=Key_Fixer
RM_nameScript=ARM_Repo_Moder
nJS_nameScript=ARM_NodeJS_Installer
Br_nameScript=ARM_Bramble_Installer
echo "$LM_nameScript is running"
echo "variables for user and home directories" 
 : ${USER?} ${HOME?} 
echo "user is : $USER"
echo "home directory is $HOME"
echo "finding the name of this script and store it to a variable"
LM_fullScriptPath="$(readlink -f $0)"
# deleat last componit from this script and store to another variable
LM_ScriptDirectory="$(dirname $LM_fullScriptPath)"
# print curent working directory then print the newly set variables
echo "Your curent working directory is : $PWD"
echo "The full name and path $LM_nameScript script is : $LM_fullScriptPath"
echo "The just the path to $LM_nameScript is : $LM_ScriptDirectory"
LM_componitPath=$LM_ScriptDirectory/Install_Scripts/Components
LM_downloadPath=$LM_ScriptDirectory/Download
LM_runPath=$LM_ScriptDirectory/Install_Scripts
echo "$LM_nameScript will use the following file path for script componits"
echo "$LM_componitPath"
echo "$LM_nameScript will use the following file path for downloading files"
echo "$LM_downloadPath"
echo "__________________"
echo "This script is written in the hopes that it will be found useful" 
echo "But without waranty. Use $LM_nameScript to install many extras to your" 
echo "ARM Linux Operating System" 
echo "__________________"
{ 
# confirm with the user 
read -r -p "Do you wish to continue? [y/N] " response 
case "$response" in 
	[yY][eE][sS]|[yY]) 
# if yes, then start risking changes 
		;; 
	*) 
#		 Otherwise exit.. 
	echo "Good Night" 
	exit 
	;; 
esac
} 
echo "making directories"
mkdir -p $LM_componitPath
mkdir -p $LM_downloadPath
# Prompt for which scripts to download or run
echo "$LM_nameScript can download and or run the following"
echo "0 - exit"
echo "1 - run $JD_nameScript [Options 3 and 4 within working]"
echo "2 - run $JDK7sf_nameScript [working]"
echo "3 - run $JDK7hf_nameScript [untested but should work]"
echo "4 - run $MT_nameScript [mostly working]"
echo "5 - run $jM_nameScript [untested]"
echo "6 - run $NF_nameScript [working]"
echo "7 - run $KF_nameScript [untested]"
echo "8 - run $RM_nameScript [untested]"
echo "9 - run $nJS_nameScript [Option 3 works for Debian Kit app users]"
echo "10 - run $Br_nameScript [untested]"
echo "11 - run $LM_nameScript mod instructions [unwritten]"
echo "________________________"
echo "Choose and input a number to continue"
echo "or input no to abort $LM_nameScript"
read -r -p "Which one thing would you like to do? " response
	if [ $response = 1 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$JD_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 2 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$JDK7sf_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 3 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$JDK7hf_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 4 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$MT_nameScript
		echo "exiting now"
		echo exit 

	elif [ $response = 5 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/$jM_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 6 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$NF_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 7 ] 
then 
		echo "this has yet to be tested"
		sh $LM_ScriptDirectory/$KF_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 8 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$RM_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 9 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$nJS_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 10 ] 
then 
		echo "this has yet to be tested"
		sh $LM_runPath/$Br_nameScript
		echo "exiting now"
		echo exit 
	elif [ $response = 11 ] 
then 
		echo "Contact the auther for assistence at either of the following links"
		echo "http://forums.rptools.net/viewtopic.php?f=12&t=24082&start=0"
		echo "http://forum.xda-developers.com/showthread.php?t=2240397"
		echo "__________________"
		echo "List of Variables being used in $LM_nameScript"
		echo "__________________"
		echo "\$LM_nameScript is : $LM_nameScript "
		echo "\$JD_nameScript is : $JD_nameScript "
		echo "\$JDK7sf_nameScript is : $JDK7sf_nameScript "
		echo "\$MT_nameScript is : $MT_nameScript "
		echo "\$jM_nameScript is : $jM_nameScript "
		echo "\$NF_nameScript is : $NF_nameScript "
		echo "\$KF_nameScript is : $KF_nameScript "
		echo "\$RM_nameScript is : $RM_nameScript "
		echo "\$USER is : $USER "
		echo "\$HOME is : $HOME "
		echo "\$LM_fullScriptPath is : $LM_fullScriptPath "
		echo "\$LM_ScriptDirectory is : $LM_ScriptDirectory "
		echo "\$LM_componitPath is : $LM_componitPath "
		echo "\$LM_downloadPath is : $LM_downloadPath "
		echo "\$LM_runPath is : $LM_runPath "
		echo "__________________"
		echo "The scripts in the Install_Scripts directory have variable declearations that are vary simular to above"
		echo "edit the part after the \= sign to change the behavior of any of these scripts"
		echo "__________________"		
		echo 
		echo "exiting now"
		echo exit 
		exit 
	elif [ $response = 0 ] 
then 
		echo "this has yet to be writen"
		echo "exiting now"
		echo exit 
		exit 
	else [ $response = * ] then 
#	 if anything else then exit 
		echo "exiting now"
		echo exit 
		exit 
	fi
exit
