#!/bin/bash
echo "This script will install node.js and NoFlo"
echo "to your ARM Linux OS"
{
# confirm with the user
read -r -p "Are you sure? [Y/n]" response
case "$response" in
  [yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
	*)
 #		 Otherwise exit..
	echo "Good Night" exit
	exit 
	;;
esac
}
# Next is setting some required variables
 : ${USER?} ${HOME?} 
# set directory variables
NF_Path=$HOME/ARM_Mod/NoFlo
njs_Path=$HOME/ARM_Mod/nodejs
# set web address variables
njs_Download=http://nodejs.org/dist/v0.10.2/node-v0.10.2-linux-arm-pi.tar.gz
# set maintenance variables
NF_Version=neadsset
njs_Version=v0.10.2
njs_bashPath=$HOME/ARM_Mod/nodejs/node-v0.10.2-linux-arm-pi
pathinto_bashrc=$HOME/.bashrc
NF_Componit_Path=$HOME/ARM_Mod/Install_Scripts/Components/NoFlo
# end of variable assignments
# make some directories for this scripts componits and for programs to be installed to
mkdir -p $NF_Componit_Path
mkdir -p $njs_Path
mkdir -p $NF_Path
# write out script componits
sudo cat > $NF_Componit_Path/Nodejs_Installer <<EOF
# download and extract node.js to $njs_Path
cd $njs_Path
wget $njs_Download
find $njs_Path type -f iname '*$njs_Version*' -print0 | xargs -0 tar -xvzf
cd ~
# append bashrc file to include the following so nodejs can be called from other programs
echo '
NODE_JS_HOME=$njs_bashPath
PATH=$PATH:$NODE_JS_HOME/bin' | sudo tee -a $pathinto_bashrc
EOF
sudo cat > $NF_Componit_Path/NoFlow_Installer <<EOF
# use npm to install NoFlo to $NF_Path
cd $NF_Path
npm install -g noflo
cd ~
EOF
sudo cat > $NF_Componit_Path/Permission_Fixer <<EOF
sudo chmod +x $NF_Componit_Path/Nodejs_Installer
sudo chmod +x $NF_Componit_Path/NoFlow_Installer
sudo chmod +x $NF_Componit_Path/Script_Runner
EOF
sudo cat > $NF_Componit_Path/Script_Runner <<EOF
sh $NF_Componit_Path/Nodejs_Installer
sh $NF_Componit_Path/NoFlow_Installer
EOF
# request permission to continue
{
# confirm with the user
read -r -p "Are you sure? [Y/n]" response
case "$response" in
  [yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
	*)
 #		 Otherwise exit..
	echo "Good Night" exit
	exit 
	;;
esac
}
# end of script
# credits
# auther of this script
# https://github.com/S0AndS0
# sources of information that where helpful in writing this script
# for node.js
# http://joshondesign.com/2013/10/23/noderpi
# for NoFlo
# https://plus.google.com/100751105859582805241/posts/iDbvbUJXHsN
