#!/bin/bash
# Make a set of scripts to download and extract Maptools and related software
This_Script=ARM_Maptools_Installer
echo "________________________________"
echo "$This_Script will download"
echo "Maptools and extract and install it"
{ 
read -r -p "Are you sure? [Y/n]" response
case "$response" in
  [yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	echo exit
	exit
	;;
esac
} 
 : ${USER?} ${HOME?} 
# Make some folders for all other operations to live in
mkdir -p $HOME/ARM_Mod/Install_Scripts/Components/Maptools
mkdir -p $HOME/ARM_Mod/Download/Maptools
mkdir -p $HOME/ARM_Mod/jApps
# file path variables start
MT_Componit_Path=$HOME/ARM_Mod/Install_Scripts/Components/Maptools
MT_Download_Path=$HOME/ARM_Mod/Download/Maptools
MT_Install_Path=$HOME/ARM_Mod/jApps
# file path variables end
# start web address variable assignment
MT_downloadVersion=http://www.rptools.net/download/zip/maptool-1.3.b87.zip
# http://www.rptools.net/download/zip/maptool-1.3.b89.zip
Download_DnD35_Pathfinder="https://www.sugarsync.com/pf/D356388_6189570_977596?directDownload=true" 
# end web address variable assignment 
# start of matenance variable assignments
pathFinderversion=MT1.3.87.06_DnD35_Pathfinder.cmpgn
MT_buildVersion=maptool-1.3.b87
MT_shortcutVersion=maptool-1.3.b87
# end of matenance variable assignments
# variable readout start
echo "You are $USER."
echo "Your home directory is $HOME."
echo "$MT_Componit_Path will be used to unpack or download script components used latter in $This_Script"
echo "$MT_Componit_Path will be used to Download source files used latter in $This_Script and others"
echo "$MT_Install_Path will be used to install new programs on your ARM Linux system"
# variable readout end
# Write a Script to download Maptools
sudo cat > $MT_Componit_Path/Maptools_Downloader <<EOF
wget -cP $MT_Download_Path/$MT_buildVersion.zip $MT_downloadVersion 
EOF
# Write a Script to extract Maptools 
sudo cat > $MT_Componit_Path/Maptools_Extractor <<EOF
cd $MT_Install_Path
find $MT_Download_Path -type f -iname 'maptool*' -print0 | xargs -0 sudo tar -vxpzf 
cd ~
EOF
# Write a script to download extras to Maptools 
sudo cat > $MT_Componit_Path/Maptools_Extras <<EOF
wget -cP $MT_Download_Path/$pathFinderversion $Download_DnD35_Pathfinder
mv $MT_Download_Path/$pathFinderversion $MT_Install_Path/maptool*
EOF
# Write a script to make short cuts on your desktop for Maptools
sudo cat > $MT_Componit_Path/Shortcut_Maker <<EOF
ln -s $MT_Install_Path/$MT_shortcutVersion $HOME/Desktop/$MT_shortcutVersion
EOF 
# Write a script to fix all permissions for this script
sudo cat > $MT_Componit_Path/Permission_Fixer <<EOF 
sudo chmod +x $MT_Componit_Path/Maptools_Downloader
sudo chmod +x $MT_Componit_Path/Maptools_Extractor
sudo chmod +x $MT_Componit_Path/Maptools_Extras
sudo chmod +x $MT_Componit_Path/Shortcut_Maker
sudo chmod +x $MT_Componit_Path/Script_Runner
EOF 
# fix permissions for Permission_Fixer
sudo chmod +x $MT_Componit_Path/Permission_Fixer 
# Write a script to make all other scripts run in proper oder
sudo cat > $MT_Componit_Path/Script_Runner <<EOF 
sh $MT_Componit_Path/Maptools_Downloader 
sh $MT_Componit_Path/Maptools_Extractor
sh $MT_Componit_Path/Maptools_Extras
sh $MT_Componit_Path/Shortcut_Maker
EOF 
echo "finished unpacking $This_Script"
{ 
read -r -p "Still want to continue? [Y/n]" response
case "$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
sh $MT_Componit_Path/Script_Runner
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	echo exit
	exit
	;;
esac
} 
exit
