#!/bin/bash
PATH=/bin:/usr/bin:/usr/local/bin ; export PATH 
umask 022
# Variables
 : ${USER?} ${HOME?} 
# find the name of this script and store it to a variable
cpuM_fullScriptPath="$(readlink -f $0)"
# deleat last componit from ThisScript and store to another variable
cpuM_ScriptDirectory="$(dirname $cpuM_fullScriptPath)"
fBatteryTemp=`dmesg | grep -E 'BATT' | awk '{gsub("Temp:""","");print $7}' | sed 's/.$//' | tail -1`
fUSB=`dmesg | grep -E 'usb' | grep -v 'off'`

mineAddress=pit.deepbit.net
default_cpuM_threadCount=1

# web addresses
sourceInfo_Link=http://linuxclues.blogspot.com/2013/08/cpuminer-build-source-debian-litecoin.html
sourceInfo_Link2=http://www.jerri.de/blog/archives/2006/05/02/scripting_screen_for_fun_and_profit/

sourceDownload_cpuminer=https://github.com/pooler/cpuminer
# functions user prompts

promptTo_continue () { 
read -r -p "Are you sure? [Y/n]" response
case "$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
	*)
 #		 Otherwise exit..
	echo "Try again? exiting.."
	exit 
	;;
esac
} 
setUserAcount_settings () { 
	echo -n "Input your $mineAddress worker's username : "
	read ui_mineAddress_username
	echo -n "Input your $mineAddress port [default was 8332] : "
	read ui_mineAddress_port
	echo -n "Input your $ui_mineAddress_username password : "
	read ui_mineAddress_password
}
ui_rootNOroot () { 
read -r -p "Are you running as root right now? [Y/n]" response
case "$response" in
	[yY][eE][sS]|[yY])
 # if yes, use apt-get for installs
 		ui_aptgetSudo="apt-get"
 		ui_conf_="./"
 		ui_teeFile="tee -a"
		;;
	*)
 #		 Otherwise use sudo apt-get for installs..
	ui_aptgetSudo="sudo apt-get"
	ui_conf_="sudo ./"
	ui_teeFile="sudo tee -a"
	;;
esac
} 
setDownload_Directory () { 
	echo "Use - home - to download to : $HOME"
	echo "Use - download - to download to : $HOME/Download"
	echo "Use - here - to download to : $cpuM_ScriptDirectory"
	echo -n "Input the directory you wish to use: "
	read ui_setDownload_Directory
	if [ $ui_setDownload_Directory = home ]
	then
		ui_Download_Directory=$HOME
		echo "$ui_Download_Directory"
	elif [ $ui_setDownload_Directory = download ]
	then 
		mkdir -p $HOME/Download
		ui_Download_Directory=$HOME/Download
		echo "$ui_Download_Directory"
	elif [ $ui_setDownload_Directory = here ]
	then 
		ui_Download_Directory=$cpuM_ScriptDirectory
		echo "$ui_Download_Directory"
	else [ $ui_setDownload_Directory = * ]
		echo "Invalid input recived, exiting now..."
		exit
	fi
} 
setOptions_cpuminerRun () { 
	
	echo "There are many options that can be set to run and checking : ./minerd -h : is a great way to more."
	echo "For now this script will display the following usefull options..."
	echo "	-x, --proxy=[PROTOCOL://]HOST[:PORT] connect through a proxy"
	echo "	-t, --threads=N number of miner threads (default: number of processors)"
	echo "	-O, --userpass=U:P username:password pair for mining server"
	echo ""
	echo "	-o : pool to connect to"
	echo "	-u : your worker name in that pool"
	echo "	-p : password for that worker"
	echo ""
	echo "A compleat working example bassed off your inputs can be found bellow..."
	echo "	./minerd -t $default_cpuM_threadCount -o $mineAddress:$ui_mineAddress_port -u $ui_mineAddress_username -p $ui_mineAddress_password"
	echo -n "How many processores are you using for mining today [1 2 3..]? "
	read ui_cpuM_threadCount
	default_cpuM_threadCount=$ui_cpuM_threadCount

# ./minerd -t $default_cpuM_threadCount -o $mineAddress:$ui_mineAddress_port -u $ui_mineAddress_username -p $ui_mineAddress_password -D
	
} 

# functions - fixed and compiled

dependsInstall_cpuminer () { 
	$ui_aptgetSudo -yq install automake
	$ui_aptgetSudo -yq install pkg-config
	$ui_aptgetSudo -yq install gcc
	$ui_aptgetSudo -yq install make
	$ui_aptgetSudo -yq install libcurl3-gnutls-dev 
} 
dependsInstall_script () { 
	$ui_aptgetSudo -yq install screen
} 

mine_with_cpuminer () { 
	cd $ui_Download_Directory
	git clone $sourceDownload_cpuminer
	cd $ui_Download_Directory/cpuminer
	$ui_conf_autogen.sh
	$ui_conf_configure CFLAGS="-O3"
	make
	

	
	cd ~
}

# script start

# script end
echo "End of script, exiting now..."
exit
# Credits

#	thanks should be given to the following link's auther for writing an easy to follow guide that works on all platforms and for being helpful even after posting :-)
http://linuxclues.blogspot.com/2013/08/cpuminer-build-source-debian-litecoin.html

# examples

#	screen command examples
# start a screen session under a given name and send a command to that newly created terminal within that screen
screen -mS testName echo "hello $USER"
# start a screen session under a given name and send a command to that newly created terminal within that screen and emidieatly detach it so the curent session remains in user view
screen -mSd testName echo "hello $USER"

# reatach with a virtical split
screen -r testName -X V
# reatach with a horizontal split
screen -r testName -X S

# end a screen and it's processes from outside the above screen name
screen -r testName -X quit


#	minerd options:
# mine with -D (degugging) to show more info
./minerd -o stratum+tcp://stratum.give-me-ltc.com:3334 -u worker -p password -D

-o : pool to connect to
-u : your worker name in that pool
-p : password for that worker

#	The usage options:
-a, --algo=ALGO specify the algorithm to use
-o, --url=URL URL of mining server
-O, --userpass=U:P username:password pair for mining server
-u, --user=USERNAME username for mining server
-p, --pass=PASSWORD password for mining server
--cert=FILE certificate for mining server using SSL
-x, --proxy=[PROTOCOL://]HOST[:PORT] connect through a proxy
-t, --threads=N number of miner threads (default: number of processors)
-r, --retries=N number of times to retry if a network call fails
(default: retry indefinitely)
-R, --retry-pause=N time to pause between retries, in seconds (default: 30)
-T, --timeout=N timeout for long polling, in seconds (default: none)
-s, --scantime=N upper bound on time spent scanning current work when
long polling is unavailable, in seconds (default: 5)
--no-longpoll disable X-Long-Polling support
--no-stratum disable X-Stratum support
--no-redirect ignore requests to change the URL of the mining server
-q, --quiet disable per-thread hashmeter output
-D, --debug enable debug output
-P, --protocol-dump verbose dump of protocol-level activities
-S, --syslog use system log for output messages
-B, --background run the miner in the background
--benchmark run in offline benchmark mode
-c, --config=FILE load a JSON-format configuration file
-V, --version display version information and exit.
-h, --help display this help text and exit.



