#!/bin/bash
PATH=/bin:/usr/bin:/usr/local/bin ; export PATH 
umask 022 		# Files that the script creates will have 755 permission.
# Thanks to Ian D. Allen, for this tip.
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
# variables auto
# find the name of this script and store it to a variable
osCN_fullScriptPath="$(readlink -f $0)"
# deleat last componit from ThisScript and store to another variable
osCN_ScriptDirectory="$(dirname $osCN_fullScriptPath)"
IP_inet_addr=`/sbin/ifconfig | grep -E 'inet addr' | grep -v '127.0.0.1' | awk '{gsub("addr:",""); print $2}'`
IP_Bcast_addr=`/sbin/ifconfig | grep -E 'Bcast' | grep -v '127.0.0.1' | awk '{gsub("Bcast:",""); print $3}'`
IP_Mask_addr=`/sbin/ifconfig | grep -E 'Mask' | grep -v '127.0.0.1' | awk '{gsub("Mask:",""); print $4}'`
IP_inet6_addr=`/sbin/ifconfig | grep -E 'inet6 addr' | grep -v '127.0.0.1' | grep -v '1/128' | awk '{gsub("addr:",""); print $2}'`
IP_local=`/sbin/ifconfig | grep -E 'inet addr' | grep -E '127.0.0.1' | awk '{gsub("addr:",""); print $2}'`
trimIP=`$IP_Bcast_addr | sed 's/...$//'`
trimRoute=`route -n | grep -E 'UG' | awk '{print $2}'`
IPmin=1
IPmax=254
customPinger=`for ip in $(seq $IPmin $IPmax) ;do (ping -c 1 -w 5 $trimIP$ip >/dev/null && echo "$trimIP$ip" &) ; done`
fLive_IPs=`$customPinger | grep -v '$trimRoute' | grep -v '$IP_inet_addr'`
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
part00_readme () { 
	echo "This script was made posible by the following links:"
	echo "https://github.com/reusserl/OpenStack-Install-Guide/blob/master/OpenStack_Havana_Debian_Wheezy_Install_Guide.rst"
	echo "	the above link realy should get most of the creadit for this version of the script."
	echo "	as I gain greater understanding of installing Openstack these scripts will become more automated."
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	echo "This script will atempt to make the process of installing and configuring Openstack an easier one."
	echo "Your - inernet IPv4 - is : $IP_inet_addr"
	echo "Your - broadcast IP - is : $IP_Bcast_addr"
	echo "Your - mask IP - is : $IP_Mask_addr"
	echo "Your - internet IPv6 - is : $IP_inet6_addr"
	echo "Your - local IP - is : $IP_local"
	echo "The - live IPs - on your network are : $fLive_IPs"
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
} 

part01_prepareDebian () { 
	echo "Adding Havana repositories."
	echo "deb http://havana.pkgs.enovance.com/debian havana main
	deb http://archive.gplhost.com/debian havana-backports main" > /etc/apt/sources.list.d/openstack.list
	echo "adding gplhost key"
	apt-get install -y gplhost-archive-keyring
	echo "adding enovance key"
	wget -qO - http://havana.pkgs.enovance.com/debian/dists/havana/pubkey.gpg | apt-key add -
	apt-key list
	echo "Updating and upgrading your system"
	apt-get update && apt-get -y dist-upgrade
	echo "Prompting for user input for : DNS Resolution : an example is presented bellow."
	echo "_________"
	echo "domain yourdomain.ch"
	echo "nameserver 8.8.8.8"
	echo "nameserver 8.8.4.4"
	echo "_________"
	echo -n "Please input : yourdomain : for : /etc/resolv.conf"
	read ui_domain
	echo -n "Please input a : nameserver : for : /etc/resolv.conf"
	read ui_nameserver
	echo -n "Please input the first : IP : for : /etc/resolv.conf"
	read ui_nameserverIP1
	echo -n "Please input the second : IP : for : /etc/resolv.conf"
	read ui_nameserverIP2
	echo 'domain $ui_domain.ch
	$ui_nameserver $ui_nameserverIP1
	$ui_nameserver $ui_nameserverIP2' > /etc/resolv.conf
	echo "Appending : /root/.bashrc : with the following:"
	echo '
	HISTSIZE=1000000
	HISTFILESIZE=9999999
	HISTTIMEFORMAT=(%d.%m.%Y) %H:%M
	export HISTSIZE HISTFILESIZE HISTTIMEFORMAT' >> /root/.bashrc
	echo "Removing Exim and installing Postfix"
	apt-get -y install postfix
	dpkg --purge exim4 exim4-base exim4-config exim4-daemon-light
	echo "Activaing mail forwarding"
	echo -n "Please enter your full email address"
	read ui_email
	echo "root: $ui_email.ch" >>/etc/aliases
	newaliases
	/etc/init.d/postfix reload
	echo "Removing unneeded software"
	dpkg --purge nfs-common rpcbind
	echo "Installing some useful tools"
	apt-get install ethtool tcpdump
	echo "Activating VLAN’s"
	apt-get install vlan
	echo "
	# vlan's
	8021q
	" >> /etc/modules
	modprobe 8021q
	echo "Enabling injection"
	echo "	To enable key-file, network & metadata injection into instances images."
	echo "nbd max_part=65" >> /etc/modules
	modprobe nbd max_part=65
	echo "Installing ntp service"
	apt-get install -y ntp
	echo "	Checking if ntp is working"
	ntpq -pn
} 
part02_IP_Forwarding () { 
	echo "Enabeling IP forwarding with the following command"
	echo "sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf"
	sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
} 
part03_nicks () { 
	echo "3 NICs must be present, for example:"
	echo "	in : /etc/network/interfaces"
	echo "__________"
	echo "	# OpenStack management"
	echo "	auto eth0"
	echo "	iface eth0 inet static"
	echo "	address 10.10.10.52"
	echo "	netmask 255.255.255.0"
	echo ""
	echo "	# VM Configuration"
	echo "	auto eth1"
	echo "	iface eth1 inet static"
	echo "	address 10.20.20.52"
	echo "	netmask 255.255.255.0"
	echo ""
	echo "	# VM internet Access"
	echo "	auto eth2"
	echo "	iface eth2 inet static"
	echo "	address 192.168.100.52"
	echo "	netmask 255.255.255.0"
	echo "__________"
	vim /etc/network/interfaces
} 
part04_openVSwitch () { 
	echo "Installing the openVSwitch"
	apt-get -y install openvswitch-switch openvswitch-datapath-dkms
	echo "__________"
	echo "Creating the bridges"
	echo "br-int will be used for VM integration"
	ovs-vsctl add-br br-int
	echo "br-ex is used to make to VM accessible from the internet"
	ovs-vsctl add-br br-ex
	echo "Displaying modifications to ovs-vsctl..."
	ovs-vsctl show
} 
part05_Neutron1 () { 
	echo "Installing the Neutron openvswitch agent, l3 agent and dhcp agent"
	echo "	Remember : Name of the region to be used by the metadata server: RegionOne : Unless you changed it for some reason."
	apt-get -y install neutron-plugin-openvswitch-agent neutron-dhcp-agent neutron-l3-agent neutron-metadata-agent
	echo "Edit /etc/neutron/api-paste.ini as shown bellow"
	echo "	Note if running Controler node on a seperat device you'll likely want to referance your notes on that node for the following fealds"
	echo "__________"
	echo "	[filter:authtoken]"
	echo "	paste.filter_factory = keystoneclient.middleware.auth_token:filter_factory"
	echo "	auth_host = 10.10.10.51"
	echo "	auth_port = 35357"
	echo "	auth_protocol = http"
	echo "	admin_tenant_name = service"
	echo "	admin_user = neutron"
	echo "	admin_password = servicePass123"
	echo "__________"
	vim /etc/neutron/api-paste.ini
	echo "Edit the OVS plugin configuration file /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini with the following examples"
	echo "	Note the following values will nead editing on your part"
	echo "	tunnel_id_ranges , local_ip"
	echo "__________"
	echo "	#Under the database section"
	echo "	[DATABASE]"
	echo "	sql_connection = mysql://neutronUser:neutronPass@10.10.10.51/neutron"
	echo ""
	echo "	#Under the OVS section"
	echo "	[OVS]"
	echo "	tenant_network_type = gre"
	echo "	tunnel_id_ranges = 1:1000"
	echo "	integration_bridge = br-int"
	echo "	tunnel_bridge = br-tun"
	echo "	local_ip = 10.20.20.52"
	echo "	enable_tunneling = True"
	echo ""
	echo "	#Firewall driver for realizing neutron security group function"
	echo "	[SECURITYGROUP]"
	echo "	firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver"
	echo "__________"
	vim /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
	echo "Update /etc/neutron/metadata_agent.ini with the following example"
	echo "	Note the following values will nead to be edited by you:"
	echo "	auth_url (both the IP and port) , auth_region (if it was changed) , admin_password , nova_metadata_ip , metadata_proxy_shared_secret"
	echo "__________"
	echo "	# The neutron user information for accessing the neutron API."
	echo "	auth_url = http://10.10.10.51:35357/v2.0"
	echo "	auth_region = RegionOne"
	echo "	admin_tenant_name = service"
	echo "	admin_user = neutron"
	echo "	admin_password = servicePass123"
	echo ""
	echo "	# IP address used by Nova metadata server"
	echo "	nova_metadata_ip = 10.10.10.51"
	echo ""
	echo "	# TCP Port used by Nova metadata server"
	echo "	nova_metadata_port = 8775"
	echo ""
	echo "metadata_proxy_shared_secret = helloOpenStack123"
	echo "__________"
	vim /etc/neutron/metadata_agent.ini
	echo "Make sure that your rabbitMQ IP in /etc/neutron/neutron.conf is set to the controller node with the following example"
	echo "	Note the following values will nead your editing"
	echo "	rabbit_host , auth_host , auth_port , admin_password"
	echo "__________"
	echo "	rabbit_host = 10.10.10.51"
	echo "	notification_driver = neutron.openstack.common.notifier.rabbit_notifier"
	echo "	allow_overlapping_ips = True"
	echo ""
	echo "	#And update the keystone_authtoken section"
	echo ""
	echo "	[keystone_authtoken]"
	echo "	auth_host = 10.10.10.51"
	echo "	auth_port = 35357"
	echo "	auth_protocol = http"
	echo "	admin_tenant_name = service"
	echo "	admin_user = neutron"
	echo "	admin_password = servicePass123"
	echo "	signing_dir = /var/lib/neutron/keystone-signing"
	echo "__________"
	vim /etc/neutron/neutron.conf
	echo "Edit dhcp_agent.ini under : /etc/neutron? as shown"
	echo "__________"
	echo "	interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver"
	echo "__________"
	vim /etc/neutron/dhcp_agent.ini
	echo "Edit /etc/sudoers.d/neutron_sudoers to give it full access like this (This is unfortunatly mandatory) as shown"
	echo "__________"
	echo "	visudo -f /etc/sudoers.d/neutron_sudoers"
	echo ""
	echo "	#Modify the neutron user"
	echo "	neutron ALL=NOPASSWD: ALL"
	echo "__________"
	vim /etc/sudoers.d/neutron_sudoers
	echo "Restarting all the services"
	cd /etc/init.d/; for i in $( ls neutron-* ); do sudo service $i restart; done; cd -
} 
part06_Neutron2 () { 
	echo "Edit the eth2 in /etc/network/interfaces as shown"
	echo "__________"
	echo "	# VM internet Access"
	echo "	auto eth2"
	echo "	iface eth2 inet manual"
	echo "	   up ifconfig $IFACE 0.0.0.0 up"
	echo "	   up ip link set $IFACE promisc on"
	echo "	   down ip link set $IFACE promisc off"
	echo "	   down ifconfig $IFACE down"
	echo "__________"
	vim /etc/network/interfaces
	echo "Add the eth2 to the br-ex as shown"
	echo "__________"
	echo "	Internet connectivity will be lost after this step but this won't affect OpenStack's work"
	ovs-vsctl add-port br-ex eth2
	echo ""
	echo "Now check if the port eth1.950 was added to br-ex"
	ovs-vsctl show
	echo ""
	echo "If you want to get internet connection back, you can assign the eth2 IP address to the br-ex interface manually"
	echo "	ifconfig br-ex 192.168.100.51 netmask 255.255.255.0 up"
	echo ""
	echo "To keep it permanent, add the following lines to /etc/rc.local"
	echo "	/sbin/ifconfig br-ex up"
	echo "	/sbin/ip addr add 192.168.100.51/24 dev br-ex"
	echo "	# optional # /sbin/ip route add default via 192.168.100.1"
	echo ""
	echo "Configuring this address in /etc/network/interfaces will not work, because openvswitch creates the br-ex interface and not brctl."
	echo "__________"
	echo "Giving you the option to add the above lines to /etc/rc.local"
	vim /etc/rc.local
} 
echo "Default variables set and functions assigned, starting script now..."
{ 
read -r -p "Do you wish to proced? [Y/n] " response
case "$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
		part00_readme
		part01_prepareDebian
		part02_IP_Forwarding
		part03_nicks
		part04_openVSwitch
		part05_Neutron1
		part06_Neutron2
		;;
	*)
 #		 Otherwise exit..
	echo "Try again? exiting.."
	exit 
	;;
esac
} 
echo "End of script. Exiting now..."
exit

