#!/bin/bash
# Make a set of scripts to download and extract Maptools and related software
echo "__________________"
echo "declaring variabls..."
MT_nameScript=ARM_Maptools_Installer
JD_nameScript=ARM_JREorJDK7_Downloader
# find the name of this script and store it to a variable
MT_fullScriptPath="$(readlink -f $0)"
# deleat last componit from MT_fullScriptPath and store to another variable
PathTo_MT="$(dirname $MT_fullScriptPath)"
# print curent working directory then print the newly set variables
echo "Your curent working directory is : $PWD"
echo "The name of this script is : $MT_fullScriptPath"
echo "The path to this script is : $PathTo_MT"
 : ${USER?} ${HOME?} 
# start of matenance variable assignments
pathFinderversion=MT1.3.87.06_DnD35_Pathfinder.cmpgn
MT_buildVersion=maptool-1.3.b87
MT_shortcutVersion=maptool-1.3.b87.jar
MT_findVersion=maptool
MT_downloadVersion=http://www.rptools.net/download/zip/maptool-1.3.b87.zip
Download_DnD35_Pathfinder=https://www.sugarsync.com/pf/D356388_6189570_977596?directDownload=true
pathFinderversion=Pathfinder.cmpn
Download_tokenTool=http://www.rptools.net/download/zip/tokentool-1.0.b28.zip
tokenTool_Version=tokentool-1.0.b28.zip
Download_initiativeTool=http://www.rptools.net/download/zip/initiativetool-1.1.b9.zip
initiativeTool_Version=initiativetool-1.1.b9.zip
Download_characterTool=http://www.rptools.net/download/zip/chartool-1.0.b15.zip
characterTool_Version=chartool-1.0.b15.zip
Download_diceTool=http://www.rptools.net/download/zip/dicetool-1.0.b34.zip
diceTool_Version=dicetool-1.0.b34.zip
Download_PCGen=http://sourceforge.net/projects/pcgen/files/latest/download?source=files
PCGen_Version=pcGen60200.zip
# end of matenance variable assignments
# file path variables start
MT_Componit_Path=$PathTo_MT/Components/Maptools
MT_Download_Path=$PathTo_MT/Download/Maptools
MT_JavaSource_Path=$PathTo_MT/Download
MT_Install_Path=$PathTo_MT/jApps/$MT_buildVersion
jApps_Install_Path=$PathTo_MT/jApps
# file path variables end
# variable readout start
echo "You are $USER."
echo "Your home directory is $HOME."
echo "________________________________"
echo "$MT_nameScript will download"
echo "Maptools and extract and install it"
{ 
read -r -p "Are you sure? [Y/n]" response
case "$response" in
  [yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	echo exit
	exit
	;;
esac
} 
# Make some folders for all other operations to live in
mkdir -p $MT_Componit_Path
mkdir -p MT_Download_Path
mkdir -p $MT_Install_Path
echo "writing Maptools_Downloader"
sudo cat > $MT_Componit_Path/Maptools_Downloader <<EOF
wget -cP $MT_Download_Path/ $MT_downloadVersion 
EOF
echo "writing Maptools_Extractor"
sudo cat > $MT_Componit_Path/Maptools_Extractor <<EOF
cd $MT_Install_Path
find $MT_Download_Path -type f -iname '$MT_findVersion*' -print0 | xargs -0 sudo unzip 
cd ~
EOF
echo "writing Maptools_Extras"
sudo cat > $MT_Componit_Path/Maptools_Extras <<EOF
echo "$MT_nameScript can download and or run the following"
echo "0 - exit"
echo "1 - Download $pathFinderversion [untested]"
echo "2 - Download $tokenTool_Version [untested]"
echo "3 - Download $initiativeTool_Version [untested]"
echo "4 - Download $characterTool_Version [untested]"
echo "5 - Download $diceTool_Version [untested]"
echo "6 - Download $PCGen_Version [untested]"
echo "7 - Download all available [untested]"
read -r -p "Which one thing would you like to do? " response
	if [ \$response = 1 ] 
then 
echo "Downloading $pathFinderversion..."
wget -cP $MT_Download_Path/$pathFinderversion $Download_DnD35_Pathfinder
echo "Moving $pathFinderversion to $MT_Install_Path"
mv $MT_Download_Path/$pathFinderversion $MT_Install_Path/$MT_buildVersion/$pathFinderversion
	elif [ \$response = 2 ] 
then 
echo "Downloading $tokenTool_Version..."
wget -cP $MT_Download_Path/$tokenTool_Version $Download_tokenTool
echo "Moving $tokenTool_Version to $MT_Install_Path"
mv $MT_Download_Path/$tokenTool_Version $MT_Install_Path/$MT_buildVersion/$tokenTool_Version
	elif [ \$response = 3 ] 
then 
echo "Downloading $initiativeTool_Version..."
wget -cP $MT_Download_Path/$initiativeTool_Version $Download_initiativeTool
echo "Moving $initiativeTool_Version to $MT_Install_Path"
mv $MT_Download_Path/$initiativeTool_Version $MT_Install_Path/$MT_buildVersion/$initiativeTool_Version
	elif [ \$response = 4 ] 
then 
echo "Downloading $characterTool_Version..."
wget -cP $MT_Download_Path/$characterTool_Version $Download_characterTool
echo "Moving $characterTool_Version to $MT_Install_Path"
mv $MT_Download_Path/$characterTool_Version $MT_Install_Path/$MT_buildVersion/$characterTool_Version
	elif [ \$response = 5 ] 
then 
echo "Downloading $diceTool_Version..."
wget -cP $MT_Download_Path/$Download_PCGen $Download_diceTool
echo "Moving $diceTool_Version to $MT_Install_Path"
mv $MT_Download_Path/$diceTool_Version $MT_Install_Path/$MT_buildVersion/$diceTool_Version
	elif [ \$response = 6 ] 
then 
echo "Downloading $PCGen_Version..."
wget -cP $MT_Download_Path/$PCGen_Version $Download_PCGen
echo "Moving $PCGen_Version to $jApps_Install_Path"
mv $MT_Download_Path/$PCGen_Version $jApps_Install_Path/$MT_buildVersion/$PCGen_Version
echo "Changing directories and unziping there"
cd $jApps_Install_Path
unzip $PCGen_Version
cd ~
	elif [ \$response = 7 ] 
then 
wget -cP $MT_Download_Path/$pathFinderversion $Download_DnD35_Pathfinder
mv $MT_Download_Path/$pathFinderversion $MT_Install_Path/$MT_buildVersion/$pathFinderversion
wget -cP $MT_Download_Path/$tokenTool_Version $Download_tokenTool
mv $MT_Download_Path/$tokenTool_Version $MT_Install_Path/$MT_buildVersion/$tokenTool_Version
wget -cP $MT_Download_Path/$initiativeTool_Version $Download_initiativeTool
mv $MT_Download_Path/$initiativeTool_Version $MT_Install_Path/$MT_buildVersion/$initiativeTool_Version
wget -cP $MT_Download_Path/$characterTool_Version $Download_characterTool
mv $MT_Download_Path/$characterTool_Version $MT_Install_Path/$MT_buildVersion/$characterTool_Version
wget -cP $MT_Download_Path/$diceTool_Version $Download_diceTool
mv $MT_Download_Path/$diceTool_Version $MT_Install_Path/$MT_buildVersion/$diceTool_Version
wget -cP $MT_Download_Path/$tokenTool_Version $PCGen_Version
mv $MT_Download_Path/$PCGen_Version $jApps_Install_Path/$MT_buildVersion/$PCGen_Version
	elif [ \$response = 0 ] 
then 
		echo "this has yet to be writen"
		echo "exiting now"
		echo exit 
		exit 
	else [ \$response = * ] then 
#	 if anything else then exit 
		echo "exiting now"
		echo exit 
		exit 
	fi
echo "End of Maptools_Extras"
EOF
echo "writing Shortcut_Maker"
sudo cat > $MT_Componit_Path/Shortcut_Maker <<EOF
ln -s $MT_Install_Path/$MT_shortcutVersion $HOME/Desktop/$MT_buildVersion 
EOF
sudo cat > $MT_Componit_Path/Download_Prompter <<EOF
echo "listing contents of : $MT_JavaSource_Path"
ls $MT_JavaSource_Path
echo "At the next prompt answer yes if you nead to run the $JD_nameScript first"
echo "and select option 4 when promted"
echo "otherwise answer no to continue with the installation prosess"
{
# alert to what's about to happen
echo "________________________________"
# confirm with the user
read -r -p "Do you still need to download JDKsf? [Y/n] " response
case "\$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
 		sh $PathTo_MT/$JD_nameScript
		;;
	*)
#		 Otherwise continue on
	echo "Moving on with $MT_nameScript"
	;;
esac
} 
EOF
echo "writing Permission_Fixer"
sudo cat > $MT_Componit_Path/Permission_Fixer <<EOF
sudo chmod +x $MT_Componit_Path/Download_Prompter
sudo chmod +x $MT_Componit_Path/Maptools_Downloader
sudo chmod +x $MT_Componit_Path/Maptools_Extractor
sudo chmod +x $MT_Componit_Path/Maptools_Extras
sudo chmod +x $MT_Componit_Path/Shortcut_Maker
sudo chmod +x $MT_Componit_Path/Script_Runner
EOF
echo "fixing permissions for Permission_Fixer"
sudo chmod +x $MT_Componit_Path/Permission_Fixer 
echo "writing Script_Runner"
sudo cat > $MT_Componit_Path/Script_Runner <<EOF
sh $MT_Componit_Path/Download_Prompter
sh $MT_Componit_Path/Maptools_Downloader 
sh $MT_Componit_Path/Maptools_Extractor
sh $MT_Componit_Path/Maptools_Extras
sh $MT_Componit_Path/Shortcut_Maker
EOF
echo "finished unpacking $MT_nameScript"
{ 
read -r -p "Still want to continue? [Y/n]" response
case "$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
sh $MT_Componit_Path/Script_Runner
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	echo exit
	exit
	;;
esac
} 
exit
