#!/bin/bash
JDK7sf_nameScript=ARM_JDKsf_Installer
JD_nameScript=ARM_JREorJDK7_Downloader
LM_nameScript=ARM_Linux_Moder
echo "$JDK7sf_nameScript is running"
 : ${USER?} ${HOME?} 
echo "user is : $USER"
echo "home directory is : $HOME"
echo "finding the name of this script and store it to a variable"
JDK7sf_fullScriptPath="$(readlink -f $0)"
# delete last componit from this script and store to another variable
JDK7sf_ScriptDirectory="$(dirname $JDK7sf_fullScriptPath)"
# print curent working directory then print the newly set variables
echo "Your curent working directory is : $PWD"
echo "The name of this script is : $JDK7sf_fullScriptPath"
echo "The path to this script is : $JDK7sf_ScriptDirectory"
echo "setting componit path variable"
JDK7sf_componitPath=$JDK7sf_ScriptDirectory/Components/JDK7sf_Installer
JDK7sf_downloadPath=$JDK7sf_ScriptDirectory/Download
JDKsf_Destanation=/usr/lib/jvm
JDKsf_Version=jdk-7u51
JDKsf_ShortcutVersion=jdk1.7.0_51
echo "$JDK7sf_nameScript will use the following file path for script componits"
echo "$JDK7sf_componitPath"
echo "$JDK7sf_nameScript will use the following file path for downloading files"
echo "$JDK7sf_downloadPath"
echo "JDK soft float destanation is"
echo "$JDKsf_Destanation"
echo "setting matenance variables are"
echo "$JDKsf_Version for Java JDK soft float version"
echo "and $JDKsf_ShortcutVersion for creating a symbolic link"
javajdkSF_targetFile=jdk-7u51-linux-arm-vfp-sflt.tar.gz
# end of variable assignment
echo "__________________"
echo "This script is written in the hopes that it will be found useful" 
echo "But without waranty. Use $JDK7sf_nameScript to install Java 7 soft float to your" 
echo "ARM Linux Operating System running Debian Squeeze" 
echo "__________________"
{
echo "You're about to install Java 7 soft float"
read -r -p "Are you sure? [Y/n] " response
case "$response" in
  [yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
 # if anything else then exit
	*)
 #		 Otherwise exit..
	echo "Good Night" exit
	exit 
	;;
esac
}
echo "__________________"
echo "Creating directories for JVM to be installed to using sudo"
sudo mkdir -p $JDKsf_Destanation
echo "Making directory for componits to be writen too"
mkdir -p $JDK7sf_componitPath
echo "__________________"
echo "unpacking components of this script"
echo "creating a list of packages to install to your system"
sudo cat > $JDK7sf_componitPath/Depends_Install_List <<EOF
sudo apt-get install -y java-common
# sudo apt-get install -y libc6-armel
# sudo apt-get install -y libsfgcc1
# sudo apt-get install -y libsfstdc++6
EOF
sudo cat > $JDK7sf_componitPath/Java_Source_copyExtracter <<EOF
# Find the tarball for $JDKsf_Version
find $JDK7sf_downloadPath -type f -iname '$JDKsf_Version*' -print0 | xargs -0 ls 
# confirm with user
{
echo "________________________________"
echo "if $JDKsf_Version was downloaded elsewhere then manually move it before procieding..."
echo "input y or yes to continue"
# confirm with the user
read -r -p "Are you ready? [Y/n] " response
case "\$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	exit
	;;
esac
} 
# echo "moving on to copying java to $JDKsf_Destanation and extracting there"
# echo "Finding and Copying Java tarball from the $JDK7sf_downloadPath directory to your $JDKsf_Destanation directory"
# find $JDK7sf_downloadPath -type f -iname '$JDKsf_Version*' -print0 | xargs -0 sudo cp --interactive --verbose --target-directory=$JDKsf_Destanation
# echo "Finding and changing ownership of Java tarball in your $JDKsf_Destanation directory"
# find $JDKsf_Destanation -type f -iname '$JDKsf_Version*' -print0 | xargs -0 sudo chown $USER:$USER
# echo "Finding and changing permissions of Java tarball in $JDKsf_Destanation directory to read write and execute for $USER"
# find $JDKsf_Destanation -type f -iname '$JDKsf_Version*' -print0 | xargs -0 sudo chmod --changes --recursive 755
# echo "Changing directories temperaraly to $JDKsf_Destanation for extraction process"
# find $JDKsf_Destanation -type f -iname '$JDKsf_Version*' -print0 | xargs -0 sudo tar -vxpzf $JDKsf_Destanation
# --verbose --extract --gunzip --file=
# echo "Creating a symbolic link in $JDKsf_Destanation named java-7-oracle"
# sudo ln -s $JDKsf_Destanation/$JDKsf_ShortcutVersion java-7-oracle
sudo tar -vxpzf $JDK7sf_downloadPath/$javajdkSF_targetFile -C $JDKsf_Destanation
sudo chmod --changes --recursive 755 $JDKsf_Destanation/$JDKsf_ShortcutVersion
sudo chown -Rc $USER:$USER $JDKsf_Destanation/$JDKsf_ShortcutVersion
sudo ln -s $JDKsf_Destanation/$JDKsf_ShortcutVersion java-7-oracle
EOF
echo "creating a list of alternatives to install for JDK tools to your system under : $JDK7sf_componitPath/Alternatives_Install_list"
sudo cat > $JDK7sf_componitPath/Alternatives_Install_list <<EOF
sudo update-alternatives --quiet --install /usr/bin/java java /usr/lib/jvm/java-7-oracle/jre/bin/java 100
sudo update-alternatives --quiet --install /usr/bin/keytool keytool /usr/lib/jvm/java-7-oracle/jre/bin/keytool 100
sudo update-alternatives --quiet --install /usr/bin/pack200 pack200 /usr/lib/jvm/java-7-oracle/jre/bin/pack200 100
sudo update-alternatives --quiet --install /usr/bin/policytool policytool /usr/lib/jvm/java-7-oracle/jre/bin/policytool 100
sudo update-alternatives --quiet --install /usr/bin/rmid rmid /usr/lib/jvm/java-7-oracle/jre/bin/rmid 100
sudo update-alternatives --quiet --install /usr/bin/rmiregistry rmiregistry /usr/lib/jvm/java-7-oracle/jre/bin/rmiregistry 100
sudo update-alternatives --quiet --install /usr/bin/unpack200 unpack200 /usr/lib/jvm/java-7-oracle/jre/bin/unpack200 100
sudo update-alternatives --quiet --install /usr/bin/orbd orbd /usr/lib/jvm/java-7-oracle/jre/bin/orbd 100
sudo update-alternatives --quiet --install /usr/bin/servertool servertool /usr/lib/jvm/java-7-oracle/jre/bin/servertool 100
sudo update-alternatives --quiet --install /usr/bin/tnameserv tnameserv /usr/lib/jvm/java-7-oracle/jre/bin/tnameserv 100
sudo update-alternatives --quiet --install /usr/bin/jexec jexec /usr/lib/jvm/java-7-oracle/jre/lib/jexec 100
sudo update-alternatives --quiet --install /usr/bin/appletviewer appletviewer /usr/lib/jvm/java-7-oracle/bin/appletviewer 100 --slave /usr/share/man/man1/appletviewer.1 appletviewer.1 /usr/lib/jvm/java-7-oracle/man/man1/appletviewer.1
sudo update-alternatives --quiet --install /usr/bin/apt apt /usr/lib/jvm/java-7-oracle/bin/apt 100 --slave /usr/share/man/man1/apt.1 apt.1 /usr/lib/jvm/java-7-oracle/man/man1/apt.1
sudo update-alternatives --quiet --install /usr/bin/extcheck extcheck /usr/lib/jvm/java-7-oracle/bin/extcheck 100 --slave /usr/share/man/man1/extcheck.1 extcheck.1 /usr/lib/jvm/java-7-oracle/man/man1/extcheck.1
sudo update-alternatives --quiet --install /usr/bin/idlj idlj /usr/lib/jvm/java-7-oracle/bin/idlj 100 --slave /usr/share/man/man1/idlj.1 idlj.1 /usr/lib/jvm/java-7-oracle/man/man1/idlj.1
sudo update-alternatives --quiet --install /usr/bin/jar jar /usr/lib/jvm/java-7-oracle/bin/jar 100 --slave /usr/share/man/man1/jar.1 jar.1 /usr/lib/jvm/java-7-oracle/man/man1/jar.1
sudo update-alternatives --quiet --install /usr/bin/jarsigner jarsigner /usr/lib/jvm/java-7-oracle/bin/jarsigner 100 --slave /usr/share/man/man1/jarsigner.1 jarsigner.1 /usr/lib/jvm/java-7-oracle/man/man1/jarsigner.1
sudo update-alternatives --quiet --install /usr/bin/java-rmi.cgi java-rmi.cgi /usr/lib/jvm/java-7-oracle/bin/java-rmi.cgi 100
sudo update-alternatives --quiet --install /usr/bin/javac javac /usr/lib/jvm/java-7-oracle/bin/javac 100 --slave /usr/share/man/man1/javac.1 javac.1 /usr/lib/jvm/java-7-oracle/man/man1/javac.1
sudo update-alternatives --quiet --install /usr/bin/javadoc javadoc /usr/lib/jvm/java-7-oracle/bin/javadoc 100 --slave /usr/share/man/man1/javadoc.1 javadoc.1 /usr/lib/jvm/java-7-oracle/man/man1/javadoc.1
sudo update-alternatives --quiet --install /usr/bin/javah javah /usr/lib/jvm/java-7-oracle/bin/javah 100 --slave /usr/share/man/man1/javah.1 javah.1 /usr/lib/jvm/java-7-oracle/man/man1/javah.1
sudo update-alternatives --quiet --install /usr/bin/javap javap /usr/lib/jvm/java-7-oracle/bin/javap 100 --slave /usr/share/man/man1/javap.1 javap.1 /usr/lib/jvm/java-7-oracle/man/man1/javap.1
sudo update-alternatives --quiet --install /usr/bin/jconsole jconsole /usr/lib/jvm/java-7-oracle/bin/jconsole 100 --slave /usr/share/man/man1/jconsole.1 jconsole.1 /usr/lib/jvm/java-7-oracle/man/man1/jconsole.1
sudo update-alternatives --quiet --install /usr/bin/jdb jdb /usr/lib/jvm/java-7-oracle/bin/jdb 100 --slave /usr/share/man/man1/jdb.1 jdb.1 /usr/lib/jvm/java-7-oracle/man/man1/jdb.1
sudo update-alternatives --quiet --install /usr/bin/jhat jhat /usr/lib/jvm/java-7-oracle/bin/jhat 100 --slave /usr/share/man/man1/jhat.1 jhat.1 /usr/lib/jvm/java-7-oracle/man/man1/jhat.1
sudo update-alternatives --quiet --install /usr/bin/jinfo jinfo /usr/lib/jvm/java-7-oracle/bin/jinfo 100 --slave /usr/share/man/man1/jinfo.1 jinfo.1 /usr/lib/jvm/java-7-oracle/man/man1/jinfo.1
sudo update-alternatives --quiet --install /usr/bin/jmap jmap /usr/lib/jvm/java-7-oracle/bin/jmap 100 --slave /usr/share/man/man1/jmap.1 jmap.1 /usr/lib/jvm/java-7-oracle/man/man1/jmap.1
sudo update-alternatives --quiet --install /usr/bin/jps jps /usr/lib/jvm/java-7-oracle/bin/jps 100 --slave /usr/share/man/man1/jps.1 jps.1 /usr/lib/jvm/java-7-oracle/man/man1/jps.1
sudo update-alternatives --quiet --install /usr/bin/jrunscript jrunscript /usr/lib/jvm/java-7-oracle/bin/jrunscript 100 --slave /usr/share/man/man1/jrunscript.1 jrunscript.1 /usr/lib/jvm/java-7-oracle/man/man1/jrunscript.1
sudo update-alternatives --quiet --install /usr/bin/jsadebugd jsadebugd /usr/lib/jvm/java-7-oracle/bin/jsadebugd 100 --slave /usr/share/man/man1/jsadebugd.1 jsadebugd.1 /usr/lib/jvm/java-7-oracle/man/man1/jsadebugd.1
sudo update-alternatives --quiet --install /usr/bin/jstack jstack /usr/lib/jvm/java-7-oracle/bin/jstack 100 --slave /usr/share/man/man1/jstack.1 jstack.1 /usr/lib/jvm/java-7-oracle/man/man1/jstack.1
sudo update-alternatives --quiet --install /usr/bin/jstat jstat /usr/lib/jvm/java-7-oracle/bin/jstat 100 --slave /usr/share/man/man1/jstat.1 jstat.1 /usr/lib/jvm/java-7-oracle/man/man1/jstat.1
sudo update-alternatives --quiet --install /usr/bin/jstatd jstatd /usr/lib/jvm/java-7-oracle/bin/jstatd 100 --slave /usr/share/man/man1/jstatd.1 jstatd.1 /usr/lib/jvm/java-7-oracle/man/man1/jstatd.1
sudo update-alternatives --quiet --install /usr/bin/native2ascii native2ascii /usr/lib/jvm/java-7-oracle/bin/native2ascii 100 --slave /usr/share/man/man1/native2ascii.1 native2ascii.1 /usr/lib/jvm/java-7-oracle/man/man1/native2ascii.1
sudo update-alternatives --quiet --install /usr/bin/rmic rmic /usr/lib/jvm/java-7-oracle/bin/rmic 100 --slave /usr/share/man/man1/rmic.1 rmic.1 /usr/lib/jvm/java-7-oracle/man/man1/rmic.1
sudo update-alternatives --quiet --install /usr/bin/schemagen schemagen /usr/lib/jvm/java-7-oracle/bin/schemagen 100 --slave /usr/share/man/man1/schemagen.1 schemagen.1 /usr/lib/jvm/java-7-oracle/man/man1/schemagen.1
sudo update-alternatives --quiet --install /usr/bin/serialver serialver /usr/lib/jvm/java-7-oracle/bin/serialver 100 --slave /usr/share/man/man1/serialver.1 serialver.1 /usr/lib/jvm/java-7-oracle/man/man1/serialver.1
sudo update-alternatives --quiet --install /usr/bin/wsgen wsgen /usr/lib/jvm/java-7-oracle/bin/wsgen 100 --slave /usr/share/man/man1/wsgen.1 wsgen.1 /usr/lib/jvm/java-7-oracle/man/man1/wsgen.1
sudo update-alternatives --quiet --install /usr/bin/wsimport wsimport /usr/lib/jvm/java-7-oracle/bin/wsimport 100 --slave /usr/share/man/man1/wsimport.1 wsimport.1 /usr/lib/jvm/java-7-oracle/man/man1/wsimport.1
sudo update-alternatives --quiet --install /usr/bin/xjc xjc /usr/lib/jvm/java-7-oracle/bin/xjc 100 --slave /usr/share/man/man1/xjc.1 xjc.1 /usr/lib/jvm/java-7-oracle/man/man1/xjc.1
EOF
echo "Creating script to compile the JRE/JDK description file named .java-7-oracle.jinfo to use with update-java-alternatives under : $JDK7sf_componitPath/JRE_JDK_Descriptions"
echo "which when run will write the contents to : $JDKsf_Destanation/.java-7-oracle.jinfo"
sudo cat > $JDK7sf_componitPath/JRE_JDK_Descriptions <<EOF
echo 'alias=java-7-oracle 
priority=100 
section=non-free
hl java /usr/lib/jvm/java-7-oracle/jre/bin/java
hl keytool /usr/lib/jvm/java-7-oracle/jre/bin/keytool
hl pack200 /usr/lib/jvm/java-7-oracle/jre/bin/pack200
hl rmid /usr/lib/jvm/java-7-oracle/jre/bin/rmid
hl rmiregistry /usr/lib/jvm/java-7-oracle/jre/bin/rmiregistry
hl unpack200 /usr/lib/jvm/java-7-oracle/jre/bin/unpack200
hl orbd /usr/lib/jvm/java-7-oracle/jre/bin/orbd
hl servertool /usr/lib/jvm/java-7-oracle/jre/bin/servertool
hl tnameserv /usr/lib/jvm/java-7-oracle/jre/bin/tnameserv
hl jexec /usr/lib/jvm/java-7-oracle/jre/lib/jexec
jre policytool /usr/lib/jvm/java-7-oracle/jre/bin/policytool
jdk appletviewer /usr/lib/jvm/java-7-oracle/bin/appletviewer
jdk apt /usr/lib/jvm/java-7-oracle/bin/apt
jdk extcheck /usr/lib/jvm/java-7-oracle/bin/extcheck
jdk idlj /usr/lib/jvm/java-7-oracle/bin/idlj
jdk jar /usr/lib/jvm/java-7-oracle/bin/jar
jdk jarsigner /usr/lib/jvm/java-7-oracle/bin/jarsigner
jdk java-rmi.cgi /usr/lib/jvm/java-7-oracle/bin/java-rmi.cgi
jdk javac /usr/lib/jvm/java-7-oracle/bin/javac
jdk javadoc /usr/lib/jvm/java-7-oracle/bin/javadoc
jdk javah /usr/lib/jvm/java-7-oracle/bin/javah
jdk javap /usr/lib/jvm/java-7-oracle/bin/javap
jdk jconsole /usr/lib/jvm/java-7-oracle/bin/jconsole
jdk jdb /usr/lib/jvm/java-7-oracle/bin/jdb
jdk jhat /usr/lib/jvm/java-7-oracle/bin/jhat
jdk jinfo /usr/lib/jvm/java-7-oracle/bin/jinfo
jdk jmap /usr/lib/jvm/java-7-oracle/bin/jmap
jdk jps /usr/lib/jvm/java-7-oracle/bin/jps
jdk jrunscript /usr/lib/jvm/java-7-oracle/bin/jrunscript
jdk jsadebugd /usr/lib/jvm/java-7-oracle/bin/jsadebugd
jdk jstack /usr/lib/jvm/java-7-oracle/bin/jstack
jdk jstat /usr/lib/jvm/java-7-oracle/bin/jstat
jdk jstatd /usr/lib/jvm/java-7-oracle/bin/jstatd
jdk native2ascii /usr/lib/jvm/java-7-oracle/bin/native2ascii
jdk rmic /usr/lib/jvm/java-7-oracle/bin/rmic
jdk schemagen /usr/lib/jvm/java-7-oracle/bin/schemagen
jdk serialver /usr/lib/jvm/java-7-oracle/bin/serialver
jdk wsgen /usr/lib/jvm/java-7-oracle/bin/wsgen
jdk wsimport /usr/lib/jvm/java-7-oracle/bin/wsimport
jdk xjc /usr/lib/jvm/java-7-oracle/bin/xjc' | sudo tee $JDKsf_Destanation.java-7-oracle.jinfo
EOF
echo "Now writing Java7_Activator to : $JDK7sf_componitPath/Java7_Activator"
sudo cat > $JDK7sf_componitPath/Java7_Activator <<EOF
sudo update-java-alternatives --set java-7-oracle
EOF
echo "Writing a script to prompt to download JDK if neaded to : $JDK7sf_componitPath/Download_Prompter"
sudo cat > $JDK7sf_componitPath/Download_Prompter <<EOF
echo "listing contents of : $JDK7sf_downloadPath"
ls $JDK7sf_downloadPath
echo "At the next prompt answer yes if you nead to run the $JD_nameScript first"
echo "and select option 4 when promted"
echo "otherwise answer no to continue with the installation prosess"
{
echo "________________________________"
read -r -p "Do you still need to download JDKsf? [Y/n] " response
case "\$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
 		sh $JDK7sf_ScriptDirectory/$JD_nameScript
		;;
	*)
#		 Otherwise continue on
	echo "Moving on with $JDK7sf_nameScript"
	;;
esac
} 
EOF
echo "Now writing a script that will run all scripts that were written to your system to : $JDK7sf_componitPath/Script_Runner"
sudo cat > $JDK7sf_componitPath/Script_Runner <<EOF
#!/bin/bash
set -e
# set -x
echo "_________________"
echo "running Download_Prompter"
sh $JDK7sf_componitPath/Download_Prompter
echo "_________________"
echo "you may run the package install list manually later to keep your system up to date,"
echo "to do so run $ sh $JDK7sf_componitPath/Depends_Install_List from a terminal window"
echo "for now though this script will automatically take care of the first install of all packages"
echo "runing Depends_Install_List"
sh $JDK7sf_componitPath/Depends_Install_List
echo "_________________"
echo "running Java_Source_copyExtracter"
sh $JDK7sf_componitPath/Java_Source_copyExtracter
echo "if things error out here you can always manualy set the permitions and extract with the GUI or command line"
echo "to change permissions use : sudo chown $USER:$USER : and : sudo chmod --changes --recursive 755"
echo "to copy to the corect directory use : sudo cp --interactive --verbose --target-directory=$JDKsf_Destanation"
echo "to extract use : sudo tar -vxpzf"
echo "place the full file path and name for Java in the proper places and run the above example commands"
echo "then when ready rerun $JDK7sf_componitPath/Script_Runner with : sh"
echo "and ignore when the find script fails again"
echo "_________________"
echo "you may run the package install list manually later to keep your system up to date"
echo "to do so run : sh $JDK7sf_componitPath/Alternatives_Install_list"
echo "for now though this script will automatically take care of the first install of all packages"
echo "running Alternatives_Install_list"
sh $JDK7sf_componitPath/Alternatives_Install_list
echo "_________________"
echo "running JRE_JDK_Descriptions"
sh $JDK7sf_componitPath/JRE_JDK_Descriptions
echo "you may run the JRE_JDK_Descriptions manually later to keep your system up to date"
echo "to do so run : sh $JDK7sf_componitPath/JRE_JDK_Descriptions"
echo "_________________"
echo "running Java7_Activator"
sh $JDK7sf_componitPath/Java7_Activator
echo "_________________"
echo "restarting $LM_nameScript to give options to install Java dependent software"
cd $JDK7sf_ScriptDirectory
cd ..
sh $LM_nameScript
echo "_________________"
# set +x
set +e
EOF
echo "Making a file to fix permissions for the rest of this script"
sudo cat > $JDK7sf_componitPath/Permission_Fixer <<EOF 
#!/bin/bash
# Now Fixing permissions
echo "fixing permissions for running this script"
sudo chmod +x $JDK7sf_componitPath/Download_Prompter
sudo chmod +x $JDK7sf_componitPath/Script_Runner
sudo chmod +x $JDK7sf_componitPath/Depends_Install_List
sudo chmod +x $JDK7sf_componitPath/Java_Source_copyExtracter
sudo chmod +x $JDK7sf_componitPath/Alternatives_Install_list
sudo chmod +x $JDK7sf_componitPath/JRE_JDK_Descriptions
sudo chmod +x $JDK7sf_componitPath/Java7_Activator
EOF
# Fix permissions for that file so it can run
echo "Fixing the Permissions on Permission_Fixer so it can fix all other permissions"
sudo chmod +x $JDK7sf_componitPath/Permission_Fixer
# Checks will need to be added to ensure all has downloaded and installed before the next part, for now ask the user again if they want to continue
{
# confirm manual or auto install
echo "you can now exit this script and run each individual script"
echo "from the $JDK7sf_componitPath directory"
ls $JDK7sf_componitPath
echo "or let this continue in auto mode by selecting yes"
read -r -p "Would you like to continue in auto mode? [Y/n]" response
case "$response" in
	[yY][eE][sS]|[yY])
# if yes, then run Script_Runner to auto install everything
sh $JDK7sf_componitPath/Script_Runner
# if yes, then check that Script_Runner succeeded
java -version
java -server -version
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	exit
	;;
esac
} 
echo "Installation Complete?"
echo "________________________________"
echo exit
