#!/bin/bash
PATH=/bin:/usr/bin:/usr/local/bin ; export PATH 
umask 022
# Files that the script creates will have 755 permission.
# Thanks to Ian D. Allen, for this tip.
# credits/sources/notes
# pdf on the subject
# http://www.researchgate.net/publication/228561385_A_linux_based_Bluetooth_scatternet_formation_kit_from_design_to_performance_results/file/72e7e524a723ff05c0.pdf
# jbluez downdoad
# http://sourceforge.net/projects/jbluez/files/latest/download
http://downloads.sourceforge.net/project/jbluez/jbluez/JBluez%201.0/jbluez-1.0.tar.gz?r=&ts=1397024156&use_mirror=softlayer-dal

# package list
# for bluez stack
# 	bluez-kernel bluez-libs bluez-utils bluez-sdp bluez-pan bluez-hcidump bluez-hciemu bluez-bluefw
# for gui bluetooh networking and add-hoc scatternet kit
#	j-bluez BASkit
# commands for bluez stack
# similar to ifconfig
#	hciconfig hci0
# to set up a device use the following
#	hciconfig hci0 up


# functions

# script start



