#!/bin/bash
# Make a set of scripts to download and extract Maptools and related software
echo "__________________"
echo "declaring variabls..."
MT_nameScript=ARM_Maptools_Installer
# find the name of this script and store it to a variable
MT_fullScriptPath="$(readlink -f $0)"
# deleat last componit from MT_fullScriptPath and store to another variable
PathTo_MT="$(dirname $MT_fullScriptPath)"
# print curent working directory then print the newly set variables
echo "Your curent working directory is : $PWD"
echo "The name of this script is : $MT_fullScriptPath"
echo "The path to this script is : $PathTo_MT"
 : ${USER?} ${HOME?} 
# start of matenance variable assignments
pathFinderversion=MT1.3.87.06_DnD35_Pathfinder.cmpgn
MT_buildVersion=maptool-1.3.b87
MT_shortcutVersion=maptool-1.3.b87.jar
MT_findVersion=maptool
MT_downloadVersion=http://www.rptools.net/download/zip/maptool-1.3.b87.zip
Download_DnD35_Pathfinder=https://www.sugarsync.com/pf/D356388_6189570_977596?directDownload=true
# end of matenance variable assignments
# file path variables start
MT_Componit_Path=$PathTo_MT/Components/Maptools
MT_Download_Path=$PathTo_MT/Download/Maptools
MT_Install_Path=$HOME/ARM_Mod/jApps/$MT_buildVersion
# file path variables end
# variable readout start
echo "You are $USER."
echo "Your home directory is $HOME."
echo "________________________________"
echo "$This_Script will download"
echo "Maptools and extract and install it"
{ 
read -r -p "Are you sure? [Y/n]" response
case "$response" in
  [yY][eE][sS]|[yY])
 # if yes, then start risking changes
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	echo exit
	exit
	;;
esac
} 
# Make some folders for all other operations to live in
mkdir -p $MT_Componit_Path
mkdir -p MT_Download_Path
mkdir -p $MT_Install_Path
echo "writing Maptools_Downloader"
sudo cat > $MT_Componit_Path/Maptools_Downloader <<EOF
wget -cP $MT_Download_Path/ $MT_downloadVersion 
EOF
echo "writing Maptools_Extractor"
sudo cat > $MT_Componit_Path/Maptools_Extractor <<EOF
cd $MT_Install_Path
find $MT_Download_Path -type f -iname '$MT_findVersion*' -print0 | xargs -0 sudo unzip 
cd ~
EOF
echo "writing Maptools_Extras"
sudo cat > $MT_Componit_Path/Maptools_Extras <<EOF
# wget -cP $MT_Download_Path/$pathFinderversion $Download_DnD35_Pathfinder
# mv $MT_Download_Path/$pathFinderversion $MT_Install_Path/$MT_buildVersion
echo 
EOF
echo "writing Shortcut_Maker"
sudo cat > $MT_Componit_Path/Shortcut_Maker <<EOF
ln -s $MT_Install_Path/$MT_shortcutVersion $HOME/Desktop/$MT_buildVersion 
EOF
echo "writing Permission_Fixer"
sudo cat > $MT_Componit_Path/Permission_Fixer <<EOF
sudo chmod +x $MT_Componit_Path/Maptools_Downloader
sudo chmod +x $MT_Componit_Path/Maptools_Extractor
sudo chmod +x $MT_Componit_Path/Maptools_Extras
sudo chmod +x $MT_Componit_Path/Shortcut_Maker
sudo chmod +x $MT_Componit_Path/Script_Runner
EOF
echo "fixing permissions for Permission_Fixer"
sudo chmod +x $MT_Componit_Path/Permission_Fixer 
echo "writing Script_Runner"
sudo cat > $MT_Componit_Path/Script_Runner <<EOF
sh $MT_Componit_Path/Maptools_Downloader 
sh $MT_Componit_Path/Maptools_Extractor
sh $MT_Componit_Path/Maptools_Extras
sh $MT_Componit_Path/Shortcut_Maker
EOF
echo "finished unpacking $MT_nameScript"
{ 
read -r -p "Still want to continue? [Y/n]" response
case "$response" in
	[yY][eE][sS]|[yY])
 # if yes, then start risking changes
sh $MT_Componit_Path/Script_Runner
		;;
	*)
#		 Otherwise exit..
	echo "Good Night"
	echo exit
	exit
	;;
esac
} 
exit
