#!/bin/sh
# set variables
curentDate=$(date +"%m%d%Y")
curentTime=$(date +"%H%M")
pathTo_bin=${ANDROID_DATA:-/data}/local/deb
pathTo_mnt=${ANDROID_DATA:-/data}/local/mnt
pathTo_SDcard=${EXTERNAL_STORAGE:-/sdcard}/

# end variables
# read out variables
echo "\$curentDate for android is: $curentDate"
echo "\$curentTime for android is: $curentTime"
echo "\$pathTo_bin for android is: $pathTo_bin"
echo "\$pathTo_mnt for android is: $pathTo_mnt"
echo "\$pathTo_SDcard for android is: $pathTo_SDcard"

# prompt to continue
echo "This script should be run on your Android terminal emulator"
echo "and not under the Linux terminal."
echo "This script will handle the syncing of your Android and Linux clocks"
echo "and install : andromize, andromize-lxde, openssh-server"
read -r "Which one thing would you like to do? " response
	if [ $response = 1 ] 
then 
# do something
	exampleVar=/home/test2
	echo "\$exampleVar curently is : $exampleVar"
	elif [ $response = 2 ] 
then 
# do something
	exampleVar=/home/test3
	echo "\$exampleVar curently is : $exampleVar"
	elif [ $response = 3 ] 
then 
# do something
	exampleVar=/home/test4
	echo "\$exampleVar curently is : $exampleVar"
	elif [ $response = 0 ] then
		echo "exiting now"
		echo exit 
		exit  
# do something
	elif [ $response = * ] then 
#	 if anything else then exit 
		echo "exiting now"
		echo exit 
		exit 
	fi

